### ISSUE TITLE
[debug] Allow unprivileged code to provide memory maps and custom fault handlers

### ISSUE THREAD

**Issue by AlessandroA** [ARMmbed/uvisor#145] opened 2016-02-10 13:25 UTC
With the changes introduced in https://github.com/ARMmbed/uvisor/pull/142 uVisor becomes even more hardware-agnostic.

This means that no memory map, IRQ map, LED blinking patterns are available for debugging. We should then provide APIs/mechanisms for unprivileged code to provide such information.

This may fit in the larger picture of a debug box, but for the moment I am creating this issue as an enhancement to keep track of the removed functionality.

**Comment by ciarmcom** [comment] 2016-02-19 02:55
ARM Internal Ref: IOTSFW-2083

**Comment by meriac** [comment] 2016-02-22 15:52
Closed as a duplicate of https://github.com/ARMmbed/uvisor/issues/70

**Closed by meriac** 2016-02-22 15:52 UTC
Labels: issue, mirrored
