### ISSUE TITLE
Every 2-3 interrupts a fault is generated with RTX+uVisor

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/uvisor#327] opened 2016-09-15 09:42 UTC
> I'm having an issue with with interrupts using uVisor, every 2,3 interruptions occur, it generates a fault. Without uVisor, it works fine, is it a issue within uVisor? is there a way to solve partially the problem till the release of real solution, like disable irq before a switch context then enable them again?

Code is here: https://developer.mbed.org/questions/74419/RTX-uvisor-and-interrupts/.

**Comment by meriac** [comment] 2016-09-15 12:43
Closed as a duplicate of https://github.com/ARMmbed/uvisor/issues/326

**Closed by meriac** 2016-09-15 12:43 UTC
